INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  'e062291e-55fe-4002-a90e-9f20f72582f3', 'elegant-modern-dining-haven', 'Elegant Modern Dining Haven', 'Syracuse, Connecticut', '$19,500.00',
  'Residential', '2025', 'Private Residence — North Shore', '420 sqft dining + pantry', 'Completed',
  '5 months', '["Dining","Butler’s pantry","Wine display"]'::jsonb, '["Concept & space planning","Custom dining table & seating","Stone & millwork detailing","Layered lighting design","Procurement & installation"]'::jsonb, '["Calacatta marble","Walnut veneer","Brushed bronze","Wool upholstery"]'::jsonb,
  '["Honed stone","Oil-rubbed timber","Antique mirror","Linen sheer"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Millwork","name":"Atelier North Joinery"},{"role":"Lighting","name":"Lumen & Form"},{"role":"Photography","name":"Studio Vale"}]'::jsonb, 'A narrow dining wing needed to host both weekday family meals and formal evenings without feeling either cramped or ceremonial.', 'We clarified circulation, introduced a sculptural table as the room’s center of gravity, and wrapped service functions into a discreet pantry spine.',
  'A dining room that reads as architecture first — calm, luminous, and flexible enough for every register of gathering.', 'A dining suite composed around marble, quiet metals, and seating that invites long evenings.', '["The existing dining wing suffered from fragmented storage and a table that never quite aligned with the windows. Guests felt either squeezed against the wall or stranded in the middle of the room.","Our response began with a new axis: a single stone-clad threshold separating dining from pantry, freeing the main volume for a bespoke walnut table sized to the bay.","Lighting is deliberately layered — a linear wash along the stone, a dimmable pendant cluster over the table, and concealed toe-kick glow in the pantry so service never breaks the atmosphere.","Seating mixes banquettes and freestanding chairs so the room can compress for four or expand for twelve without rearranging the architecture."]'::jsonb, 'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/3214064/pexels-photo-3214064.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'tall', true, 0, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  '1564167f-842a-413f-a3bf-1a7582e8fb33', 'minimalist-luxury-lounge', 'Minimalist Luxury Lounge', 'Syracuse, Connecticut', '$19,500.00',
  'Residential', '2024', 'Private Residence — Hillcrest', '680 sqft primary lounge', 'Completed',
  '4 months', '["Living","Media niche","Library wall"]'::jsonb, '["Full interior reconfiguration","Custom low seating system","Integrated media cabinetry","Acoustic soft finishes","Art placement & styling"]'::jsonb, '["European oak","Bouclé textile","Travertine","Powder-coated steel"]'::jsonb,
  '["White-oil oak","Limewash walls","Matte black metal","Hand-tufted rug"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Upholstery","name":"Softform Atelier"},{"role":"Stone","name":"Pietra Works"}]'::jsonb, 'The lounge felt busy — competing furniture, exposed cables, and no clear place to gather or retreat.', 'We edited ruthlessly, built storage into architecture, and composed a single conversational island with sightlines to the garden.',
  'A quiet living room with hotel-grade composure and residential softness — negative space as a luxury finish.', 'Low furniture, generous negative space, and tactile finishes define a lounge made for slow living.', '["Rather than adding more pieces, we removed half of what was there. What remained had to earn its place through proportion, tactility, or function.","A continuous oak plinth runs the length of the media wall, concealing AV, charging, and seasonal storage while reading as architecture rather than furniture.","The seating system is low and modular — deep enough for lounging, light enough visually that the room still feels generous.","Acoustics were treated with a thick rug, upholstered panels behind the sofa, and linen curtains that soften evening reflections from the glass."]'::jsonb, 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'short', true, 1, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  '291f4480-a9a2-4dcd-adfb-a25881ec7bc4', 'bright-contemporary-serenity', 'Bright Contemporary Serenity Space', 'Syracuse, Connecticut', '$19,500.00',
  'Residential', '2025', 'Private Residence — Lakeside', '1,100 sqft open living', 'Completed',
  '6 months', '["Open living","Kitchen adjacency","Morning room"]'::jsonb, '["Daylighting strategy","Pale material palette","Kitchen–living threshold","Window treatments","Furniture & décor edit"]'::jsonb, '["Limestone","Ash timber","Sheer linen","Brushed nickel"]'::jsonb,
  '["Honed limestone","Bleached ash","Mineral paint","Frosted glass"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Glazing Consultant","name":"Clearspan Daylight"},{"role":"Textiles","name":"Loom & Latitude"}]'::jsonb, 'South-facing glass brought glare and heat; the open plan felt washed-out by midday and flat by evening.', 'We treated light as a material — filtering, bouncing, and staging it through sheers, pale stone, and calibrated artificial layers.',
  'A living volume that stays luminous without glare, calm from breakfast through late dinner.', 'Soft daylight, pale textiles, and calibrated sightlines for a home that stays calm from morning to night.', '["The lakeside orientation was a gift and a liability. Unmediated sun flattened textures and heated the sofa zone by early afternoon.","Sheer linen tracks, a limestone floor with high albedo, and ash millwork bounce light deeper into the plan while cutting harsh contrast.","Evening scenes reverse the strategy: warm dimmable washes at the ceiling perimeter, discrete reading lamps, and under-shelf glow in the kitchen adjacency.","Furniture stays low and pale so the horizon and water remain the primary artwork of the room."]'::jsonb, 'https://images.pexels.com/photos/7018391/pexels-photo-7018391.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/7018391/pexels-photo-7018391.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'wide', true, 2, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  '878899dd-2711-44bd-a5e4-9171890ea2f4', 'warm-modern-comfort-living', 'Warm Modern Comfort Living', 'Syracuse, Connecticut', '$19,500.00',
  'Residential', '2024', 'Private Residence — Cedar Lane', '740 sqft living + hearth', 'Completed',
  '5 months', '["Living room","Hearth niche","Terrace link"]'::jsonb, '["Hearth redesign","Seating plan & rugs","Timber cladding","Ambient lighting scenes","Outdoor–indoor threshold"]'::jsonb, '["Smoked oak","Clay plaster","Wool & silk rug","Amber glass"]'::jsonb,
  '["Smoked timber oil","Venetian clay","Antique brass","Leather accents"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Plaster","name":"Earthtone Surfaces"},{"role":"Rug Commission","name":"Knot & Grain"}]'::jsonb, 'The living room felt cold despite a fireplace — grey finishes and scattered seating diluted any sense of gathering.', 'We rebuilt warmth through material temperature, a protective seating core, and lighting that mimics firelight after dark.',
  'A living room that feels hospitable on first entry and holds conversation without effort.', 'Ember tones, layered rugs, and sculptural lighting for a living room that feels hospitable on first entry.', '["Comfort here is compositional, not sentimental. Ember tones, clay plaster, and smoked oak create a thermal palette before anyone sits down.","The hearth niche was deepened and lined so the fire reads as architecture. Seating wraps it without blocking the terrace doors.","A custom rug anchors the conversational island; side tables in amber glass catch evening light from the pendant.","When the terrace doors open, the indoor palette continues outdoors through timber decking and matching lounge textiles."]'::jsonb, 'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/6438752/pexels-photo-6438752.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'tall', true, 3, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  '64490ead-7dab-42ac-a3a9-b1747a8cd833', 'cozy-elegant-haven', 'Cozy Elegant Haven', 'Syracuse, Connecticut', '$19,500.00',
  'Residential', '2025', 'Private Residence — Primary Suite', '510 sqft suite + dressing', 'Completed',
  '4 months', '["Bedroom","Dressing","Ensuite threshold"]'::jsonb, '["Suite planning","Custom headboard millwork","Dressing cabinetry","Circadian lighting","Textile & soft finishes"]'::jsonb, '["Upholstered panels","Rift oak","Cashmere blend","Veined marble"]'::jsonb,
  '["Matte lacquer","Brushed nickel","Blackout + sheer layers","Stone vanity"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Cabinetry","name":"Quiet Closet Co."},{"role":"Textiles","name":"Nightweave Studio"}]'::jsonb, 'The primary suite needed hotel-grade rest without losing the intimacy of a private home.', 'We zoned sleep, dress, and wash with soft thresholds, dimmable scenes, and millwork that hides clutter.',
  'A sanctuary suite where every evening ritual feels deliberate and unhurried.', 'A suite designed as a private retreat — soft textiles, dimmable scenes, and quiet luxury details.', '["Sleep architecture starts with darkness and silence. We specified dual window layers, acoustic panels behind the headboard, and carpet that quiets footfall.","The headboard millwork wraps the corners, integrating reading lights and outlets so nightstands stay clear.","Dressing is a corridor of rift-oak cabinets with soft-close hardware and jewel-box lighting that only activates when doors open.","Circadian control shifts from cool morning wash to warm amber night scenes — the suite never feels abrupt."]'::jsonb, 'https://images.pexels.com/photos/6438752/pexels-photo-6438752.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/6438752/pexels-photo-6438752.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/3990359/pexels-photo-3990359.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/6032424/pexels-photo-6032424.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/279719/pexels-photo-279719.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'short', false, 4, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  '27a3d45b-8747-43b2-ae01-a034773287ec', 'shaazzz-interior-studio', 'Shaazzz Interior Studio', 'Dubai Marina Concept', '$42,000.00',
  'Hospitality', '2025', 'Shaazzz Hospitality Group', '2,400 sqft concept suite + lounge', 'Concept delivered',
  '7 months', '["Hospitality suite","Arrival lounge","Coastal F&B niche"]'::jsonb, '["Brand-aligned concept design","FF&E specification","Guest journey mapping","Material boards & CGI","Vendor shortlisting"]'::jsonb, '["Salt-washed teak","Coral stone","Raw linen","Handblown glass"]'::jsonb,
  '["Weathered timber","Lime plaster","Rope detailing","Sea-glass mosaic"]'::jsonb, '[{"role":"Creative Direction","name":"Twentyone06 Studio"},{"role":"Hospitality Consultant","name":"Harbor Protocol"},{"role":"CGI","name":"Frame North"}]'::jsonb, 'Translate a coastal luxury brand into interiors that feel local and timeless — not themed or transient.', 'We built a material language of salt, sand, and horizon: weathered timber, soft plaster, and low furniture that keeps views primary.',
  'A concept suite and lounge language ready for multi-key rollout across the client’s marina properties.', 'Minimalist luxury interiors with premium materials, open spaces, and calming ocean-inspired elegance.', '["Hospitality interiors fail when they shout. Shaazzz needed quiet confidence — spaces that photograph well and recover quickly between guests.","The arrival lounge is a sequence of thresholds: filtered light, a low seating island, and a material sample wall that doubles as brand storytelling.","In the suite, the sleeping zone faces the water; wet areas and wardrobe are pulled into a service spine so the main volume stays clear.","FF&E specifications favor durable textiles and replaceable soft goods so operations can refresh without redesigning architecture."]'::jsonb, 'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/7018391/pexels-photo-7018391.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2440471/pexels-photo-2440471.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'wide', false, 5, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  'e2f5b253-54c1-4c8e-a175-eb172fe5db38', 'the-private-sanctuary', 'The Private Sanctuary', 'Coral Gables, FL', '$28,900.00',
  'Residential', '2023', 'Private Residence — Coral Way', '3,200 sqft interior renovation', 'Completed',
  '9 months', '["Whole-home renovation","Garden pavilion","Gallery corridor"]'::jsonb, '["Full interior renovation","Garden–house interface","Stone flooring throughout","Art lighting & hanging","Custom furniture program"]'::jsonb, '["Florida keystone","Teak","Linen & cotton","Cast bronze"]'::jsonb,
  '["Honed keystone","Natural teak oil","Mineral wash","Patina bronze"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Landscape","name":"Canopy & Court"},{"role":"Art Advisor","name":"Southern Edit"},{"role":"General Contractor","name":"Gables Build Co."}]'::jsonb, 'Open the house to lush gardens without sacrificing privacy from the street or overheating the interiors.', 'Layered thresholds, deep overhangs of soft furnishings, and a stone floor that cools underfoot while linking indoor and outdoor rooms.',
  'A residence that breathes with the garden — private, cool, and composed for collecting art and hosting slowly.', 'A perfect balance of modern design and tranquil textures, creating an elegant space for relaxation.', '["Coral Gables light is generous. We tempered it with deep reveals, sheer layers, and keystone floors that stay cool through summer.","A gallery corridor becomes the spine of the home — art lit to museum standards, with niches for sculpture that punctuate the walk to the garden pavilion.","Living spaces open through multi-slide glazing; when open, rugs and furniture alignments continue outdoors so the terrace feels like a room.","Privacy from the street is handled with layered planting and a solid entry sequence that never announces the garden beyond."]'::jsonb, 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/3555615/pexels-photo-3555615.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2440471/pexels-photo-2440471.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'tall', false, 6, true
);
INSERT INTO public.projects (
  id, slug, title, location, price, category, year, client, area, status, duration,
  typologies, scope, materials, finishes, credits, challenge, approach, outcome,
  excerpt, body, hero, gallery, span, featured, sort_order, published
) VALUES (
  'a0a22f23-fe96-4bc0-a2b3-4cabcd021146', 'the-atrium-residence', 'The Atrium Residence', 'Aspen, Colorado', '$34,200.00',
  'Residential', '2024', 'Private Residence — Red Mountain', '4,800 sqft mountain home', 'Completed',
  '11 months', '["Atrium living","Ski lounge","Primary wing"]'::jsonb, '["Interior architecture package","Timber & steel detailing","Mountain-view furniture plan","Feature lighting","Seasonal styling program"]'::jsonb, '["Reclaimed fir","Blackened steel","Shearling","Local stone"]'::jsonb,
  '["Hand-scraped timber","Waxed steel","Lime plaster","Wool throws"]'::jsonb, '[{"role":"Lead Designer","name":"Twentyone06 Studio"},{"role":"Architect of Record","name":"Peak Form Architects"},{"role":"Timber","name":"High Country Mill"},{"role":"Lighting","name":"Altitude Light Lab"}]'::jsonb, 'A dramatic atrium risked feeling like a lobby — impressive but cold, hard to furnish, difficult to heat emotionally.', 'We humanized the volume with timber warmth, soft seating islands, and lighting that draws the eye to the mountains without competing with them.',
  'An atrium that works as daily living — grounded, warm, and oriented entirely to the landscape.', 'Warm timber, sculptural lighting and floor-to-ceiling glass framing an uninterrupted mountain vista.', '["Volume without intimacy is spectacle. We introduced a timber mezzanine soffit and a low seating topography so people occupy the atrium, not just photograph it.","Blackened steel echoes the exterior structure while reclaimed fir softens every touchpoint — handrails, bench, dining shell.","Lighting is mostly architectural: grazers on timber, a single sculptural pendant over dining, and firelight as the evening focal point.","The primary wing peels away for quiet; the atrium remains the social heart for ski days and long winter dinners."]'::jsonb, 'https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1600', '["https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/3214064/pexels-photo-3214064.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200","https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1200"]'::jsonb,
  'short', false, 7, true
);