-- Seed testimonials + site settings for Twentyone06 CMS
DELETE FROM public.testimonials;

INSERT INTO public.testimonials (id, quote, name, role, image, status, sort_order, published) VALUES
(gen_random_uuid(), 'The team exceeded our expectations with their exceptional design and development skills. They truly understood our vision and brought it to life. We couldn’t be happier with the final product.', 'Steven Batchelor Frios', 'Managing Director . UN!Que Project Solutions', '', 'approved', 0, true),
(gen_random_uuid(), 'We had the pleasure of working with TwentyOne06 on an office project in Al Barsha. They are a fantastic team of professionals with amazing creativity. The project looks spectacular, we would highly recommend it if your’re looking for a unique and stand-out interior design team.', 'Havelock One Interiors', '', '', 'approved', 1, true),
(gen_random_uuid(), 'We recently had the privilege of working with TwentyOne06, and we must say, it was an exceptional experience from start to finish. They brought a level of professionalism and creativity that exceeded our expectations. Working with TwentyOne06 was an absolute pleasure! Their Professionalism, creativity, and attention to detail made our collaboration seamless and enjoyable. I highly recommend them for any design project.', 'Lylux Lighting Group', '', '', 'approved', 2, true),
(gen_random_uuid(), 'Recently had the pleasure of working with TwentyOne06, and i can confidently say they are a fantastic design company. Their commitment to authenticity and quality is evident in every aspect of their work. The team is not only highly professional but also incredibly responsive, making the entire process seamless and enjoyable. From the initial consultation to final delivery, TwentyOne06 exceeded my expectations. Their innovative designs reflect a deep understanding of client needs and current trends, resulting in truly unique and impactful solutions. If you’re looking for a design partner who values excellence and creativity, I wholeheartedly recommend TwentyOne06. They are a cut above the rest.', 'James Knight Pacheco', 'Co-Founder/Chef/Host . the Chef JKP Podcast / Culinary Consultant', '', 'approved', 3, true),
(gen_random_uuid(), 'The process of collaborating with TwentyOne06 began with them getting to know me personally and understanding where I am coming from. They adapted to my expectations while adding their own unique design input. it was a challenge for TwentyOne06 because many restaurant designers tend to replicate designs, but they didn’t. instead, they transformed the design into what it is today, which is commendable.', 'Reif Othman', 'Owner . Hotaru Holdings', '', 'approved', 4, true),
(gen_random_uuid(), 'It was a true pleasure working with TwentyOne06. Govind and his team have successfully combined our vision with their expertise and experienceto come up not only with an innovative design but most importantly a functional space whilst maximizing our resources. throughout the entire design process, TwentyOne06’s attention to detail was second to none. They were professional, flexible and understood every facet of what we wanted to capture in great detail', 'Kishore Sathar', 'General manager . Dusit Thani Hotel', '', 'approved', 5, true),
(gen_random_uuid(), 'As a seasoned F&B operator I’ve had the pleasure to have worked with the best in class pertaining to design specialists. 2106 in my opinion would be considered as best in class.... Govind and his team have demonstrated the ability to understand our vision and interpreted this in to reality. Its also worth mentioning that their ability to adapt to change is commendable and their ability to manage the appointed contractor is substantiated with depth of knowledge in materials and market trends as well as keeping our “the Client” interest at the forefront of the projects 2106 have managed for Sarood Hospitality. On behalf of Sarood I would like to thank Govind and the 2106 team for their services conducted to help drive Flow and The Noodle House Brands.', 'Steven Holloway', 'Contractors Direct . CEO', '', 'approved', 6, true),
(gen_random_uuid(), 'TwentyOne06 was the visionary force behind Reif & Tero, meticulously designing an extraordinary culinary haven that offers diners an unparalleled gastronomic experience. Light Link worked tirelessly with the team at TwentyOne06, to create 2 very different styles of dining experience for Reif Othman in the new Dubai Hills location, and WE LOVE IT! From taking initial sketches and samples of tea brushes through to truly bespoke light fittings, custom neon pendants, and wall sconces all dreamt up in the mind of Govind Shepley and the team, were brought to life by our designers and custom partners.', 'David Cook', 'Contractors Direct . CEO', '', 'approved', 7, true),
(gen_random_uuid(), 'Working with Govind and Studio TwentyOne06 has eased the processes between the client, contractor and design team alike. The clear and detailed design has aided us to execute the design intent and deliver to the agreed timetable. It’s a credit to their design teams’ understanding of the client’s business requirements, knowledge of the F&B industry and more importantly in sourcing local finishes to stay in line with Capex budget is certainly music to our ears! We’re always glad to work alongside Studio TwentyOne06 projects.', 'Esam Bacoush', 'Associate Director . Dif Interiors', '', 'approved', 8, true),
(gen_random_uuid(), 'I had the pleasure of working with Govind Shepley, Mike, Hannah, Sabiha and Satinder on Voco Monaco Lobby renovation and ELIX Spa. TwentyOne06’s creativity, hard work, passion and patience is truly inspiring on all project portfolios we collaborate on. Well done to you all!', 'Marwa Sharaky', 'Senior Design Manager . Kleindienst Group (Voco Monaco, Elix Spa)', '', 'approved', 9, true),
(gen_random_uuid(), 'What an amazing concept this is! It is such a pleasure collaborating with such a talented team like TwentyOne06 on this project. Massive congrats on taking home the Highly Commended award.', 'Pierre Engelbrecht', 'associate . Compass project Consulting', '', 'approved', 10, true),
(gen_random_uuid(), 'TwentyOne06 was the visionary force behind Reif & Tero, meticulously designing an extraordinary culinary haven that offers diners an unparalleled gastronomic experience. Light Link worked tirelessly with the team at TwentyOne06, to create 2 very different styles of dining experience for Reif Othman in the new Dubai Hills location, and WE LOVE IT! From taking initial sketches and samples of tea brushes through to truly bespoke light fittings, custom neon pendants, and wall sconces all dreamt up in the mind of Govind Shepley and the team, were brought to life by our designers and custom partners.', 'Light Link', '', '', 'approved', 11, true);

INSERT INTO public.site_settings (key, value) VALUES
('brand', '{"primary":"#e01e26","name":"Twentyone06"}'::jsonb),
('nav', '{"brand":"Twentyone06","links":[{"label":"About","to":"/about"},{"label":"Projects","to":"/projects"},{"label":"Services","to":"/services"},{"label":"Journal","to":"/journal"},{"label":"Contact","to":"/contact"}]}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
